-- Snapshot reconciliation: fork-specific tables (activation_events,
-- cloud_upstream_connections, cloud_upstream_runs) already exist from
-- earlier fork migrations; this migration only advances the snapshot.
